// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5UpFw0klXJaRmizMhjWHmOQN4gtMYobA',
    appId: '1:855351712840:web:c3983f3743784055750c7d',
    messagingSenderId: '855351712840',
    projectId: 'bimbel-app-dc47f',
    authDomain: 'bimbel-app-dc47f.firebaseapp.com',
    storageBucket: 'bimbel-app-dc47f.firebasestorage.app',
    measurementId: 'G-Q9ZBJY7R9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kbxrlSq2sPXJL9xzCo6J1APFLDIusLc',
    appId: '1:855351712840:android:09da66efdb52cff2750c7d',
    messagingSenderId: '855351712840',
    projectId: 'bimbel-app-dc47f',
    storageBucket: 'bimbel-app-dc47f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD46gs5kGJv9mR_gpeqd3KMBNaPwFiO04',
    appId: '1:855351712840:ios:7b72323c8f0efdbb750c7d',
    messagingSenderId: '855351712840',
    projectId: 'bimbel-app-dc47f',
    storageBucket: 'bimbel-app-dc47f.firebasestorage.app',
    iosBundleId: 'com.example.bimbelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD46gs5kGJv9mR_gpeqd3KMBNaPwFiO04',
    appId: '1:855351712840:ios:7b72323c8f0efdbb750c7d',
    messagingSenderId: '855351712840',
    projectId: 'bimbel-app-dc47f',
    storageBucket: 'bimbel-app-dc47f.firebasestorage.app',
    iosBundleId: 'com.example.bimbelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5UpFw0klXJaRmizMhjWHmOQN4gtMYobA',
    appId: '1:855351712840:web:b83d0636531bd632750c7d',
    messagingSenderId: '855351712840',
    projectId: 'bimbel-app-dc47f',
    authDomain: 'bimbel-app-dc47f.firebaseapp.com',
    storageBucket: 'bimbel-app-dc47f.firebasestorage.app',
    measurementId: 'G-VVGHHDTG6L',
  );
}
